# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name_of_image',
            new_name='user',
        ),
    ]
